Provide script example for implementing our own AI logic
Regression-Games/unity.bossroom-2.0.4 pull request #2
Opened 2023-04-17 17:46 UTC by vontell

Adds an entry point to drop in your own AI logic for a player. This is very much barebones - you can click "P" when in game to spawn a new bot. This can definitely be improved, but this is a good starting spot.

### Steps to get started
1. Start the Unity game
2. Click on "Change Profile", and then select the RGUnityDev profile provided from Zack's setup
3. Click "Start with Regression Games", then "Host with IP", and then "Host" (it's fine if you aren't running RG - just no RG bots will connect)
4. Select your character, and click Ready
5. When in game, click "P" to spawn a bot. You'll notice the default behavior is to just follow another player.

### What to check out to implement your own logic
1. Open up the Boss Room scene, and click the UnityBotManager GameObject. This has a script, `BotSpawner.cs`, which dictates which key presses should spawn the player prefab (in this case P).
2. Check out the `Assets/Scripts/Gameplay/RegressionGames/UnityBots/BotSpawner.cs` file. You will need to change one part in here, on line 93 - this is where you indicate your script that will control the player.
3. Open or copy `Assets/Scripts/Gameplay/RegressionGames/UnityBots/UnityBotExample.cs`. This is the file where you will implement your AI. Since it is attached to the player prefab, you can access various components such as the nav mesh agent, other player positions, etc... The current implementation simply gets all other players and chooses to follow one.
4. There are tons of other game logic pieces that need to be done when controlling a character... the animation, handling death, attack cooldowns, etc... In order to implement your bot properly, you should follow the code in `Assets/Scripts/Gameplay/GameplayObjects/Character/AI`. This shows how to not do things like changing the player position directly, but rather send a message to the server to execute the action for you. For example:

```c#
// attack!
var attackData = new ActionRequestData
{
    ActionID = m_CurAttackAction.ActionID,
    TargetIds = new ulong[] { m_Foe.NetworkObjectId },
    ShouldClose = true,
    Direction = m_Brain.GetMyServerCharacter().physicsWrapper.Transform.forward
};
m_ServerActionPlayer.PlayAction(ref attackData);
```

2023-04-17 17:53 UTC, RG-nAmKcAz requested changes

2023-04-17 17:53 UTC, RG-nAmKcAz commented on Assets/Prefabs/Character/PlayerAvatar.prefab
> +  IsBot: 0
Are we tagging the player avatar explicitly as a non-bot ?  Did a new behavior get added to the player prefab ?

Asking because I had introduced a new prefab that was specific to bots.

2023-04-17 17:53 UTC, RG-nAmKcAz commented on Assets/Scripts/Gameplay/RegressionGames/UnityBots/BotSpawner.cs
> +                // if reconnecting, set the player's position and rotation to its previous state
we can remove this commented section

2023-04-17 17:54 UTC, vontell commented on Assets/Prefabs/Character/PlayerAvatar.prefab
> +  IsBot: 0
Ah sorry, this must have sneaked in there by accident. Will fix this.

2023-04-17 17:59 UTC, RG-nAmKcAz commented on Assets/Prefabs/Character/PlayerAvatar.prefab
> +  IsBot: 0
this looks like client player avatar being saved with isBot as false explicitly, which is fine

2023-04-17 18:04 UTC, RG-nAmKcAz commented on Assets/Scripts/Gameplay/RegressionGames/UnityBots/UnityBotExample.cs
> +            navAgent.SetDestination(target.transform.position);
this code isn't valid to use in the context of BossRoom... this will bypass the server being the point of control for the game actions for players and enforcing movement limitations /etc.

Technically you 'can' do this since you're the owner of the networkobject spawned, but it is a huge no no

2023-04-17 18:40 UTC, RG-nAmKcAz commented on Assets/Scripts/Gameplay/RegressionGames/UnityBots/UnityBotExample.cs
> +        var targets = GameObject.FindGameObjectsWithTag("Player").ToList();
Looking better.

Since this will be server only, we probably want it to be `NetworkBehaviour` instead of `MonoBehaviour` and have code like this in `Start` and `Update` so that it doesn't run on the client.

```cs
            if (!IsServer)
            {
                return;
            }
```

2023-04-17 18:42 UTC, RG-nAmKcAz requested changes

2023-04-17 18:42 UTC, RG-nAmKcAz commented on Assets/Scripts/Gameplay/RegressionGames/UnityBots/UnityBotExample.cs
> +        var targets = GameObject.FindGameObjectsWithTag("Player").ToList();
Looking better.

Since this will be server only, we probably want it to be `NetworkBehaviour` instead of `MonoBehaviour` and have code like this in `Start` and `Update` so that it doesn't run on the client.

```cs
            if (!IsServer)
            {
                return;
            }
```

2023-04-18 19:44 UTC, RG-nAmKcAz approved these changes

2023-04-18 20:19 UTC, TheFleetCommander approved these changes

2023-04-18 20:42 UTC, merged